** Settings **
Library  SeleniumLibrary

** Variables **

#Elements da Pagina de Cadastro
${input_nome}           //*[@id="radix-:R3mph9:"]/div/div/div[2]/form/div/label[1]/div/input
${input_email}          //*[@id="radix-:R3mph9:"]/div/div/div[2]/form/div/label[2]/div/input
${input_senha}          //*[@id="radix-:R3mph9:"]/div/div/div[2]/form/div/label[3]/div/input
${criar_conta}          //*[@id="radix-:R3mph9:"]/div/div/div[2]/form/div/button